// Major Indian cities sorted alphabetically (Tier 1, 2, and key Tier 3)
export const INDIAN_CITIES: string[] = [
  "Agra", "Ahmedabad", "Ajmer", "Aligarh", "Allahabad", "Amritsar", "Aurangabad",
  "Bangalore", "Bareilly", "Bhilai", "Bhopal", "Bhubaneswar", "Bikaner",
  "Chandigarh", "Chennai", "Coimbatore", "Cuttack",
  "Dehradun", "Delhi", "Dhanbad", "Durgapur",
  "Erode",
  "Faridabad", "Firozabad",
  "Ghaziabad", "Goa", "Gorakhpur", "Greater Noida", "Gulbarga", "Guntur", "Gurgaon", "Guwahati", "Gwalior",
  "Hubli", "Hyderabad",
  "Indore",
  "Jabalpur", "Jaipur", "Jalandhar", "Jammu", "Jamnagar", "Jamshedpur", "Jhansi", "Jodhpur",
  "Kakinada", "Kanpur", "Kochi", "Kolhapur", "Kolkata", "Kota", "Kurnool",
  "Lucknow", "Ludhiana",
  "Madurai", "Mangalore", "Meerut", "Moradabad", "Mumbai", "Mysore",
  "Nagpur", "Nanded", "Nashik", "Navi Mumbai", "Nellore", "Noida",
  "Patna", "Pondicherry", "Pune",
  "Raipur", "Rajkot", "Ranchi", "Rourkela",
  "Salem", "Saharanpur", "Shimla", "Siliguri", "Solapur", "Srinagar", "Surat",
  "Thane", "Thiruvananthapuram", "Tiruchirappalli", "Tiruppur",
  "Udaipur", "Ujjain",
  "Vadodara", "Varanasi", "Vasai-Virar", "Vijayawada", "Visakhapatnam",
  "Warangal",
];
